### PR TITLE
Resolve OMBI Basic Auth Issue

### PR DESCRIPTION
**Pull request by addbee**
PR to resolve the issue with Ombi's auth changes

This should also solve the plex issue, you can reach the plex endpoint without the SSH tunnel.

Adds a variable to the .env file which is used to enable basic auth only on specific endpoints.

I've set it to all except for plex + ombi, since these have their own authentication by default.

.env has username test password test. Generated from htpasswd.

### CODE REVIEW

**Comment by robflate** [comment]
Thanks. This needs the following changes to work;

1. Remove `[entryPoints.https.auth.basic] usersFile = "/etc/traefik/.htpasswd"` from `traefik.toml` otherwise you get the error` level=fatal msg="Error starting server: read /etc/traefik/.htpasswd: is a directory"`.
2. Remove `traefik.frontend.auth.basic: "${HTPASSWD}"` from ombi in `docker-compose.yml`.

Thanks again. It's great to have ombi working!

**Comment by addbee** [comment]
Hi @robflate 

Thanks for the note - I got a bit paste-happy with the HTPASSWD - using the git web editor.

Next time (if necessary) i'll make sure to check out my own changes and try them first...

I've made those changes on the PR so hopefully all good to merge when @duhio reviews.

**Comment by stevewm** [comment]
Thanks @adam-bell, looks like this should resolve it the Ombi issue. Also thanks @robflate for reviewing as well - much appreciated.

It looks like it doesn't change the requirement to use an SSH tunnel to set Plex - at least not when I've given it a quick test. That being said, it could be due to having an existing account with a server already associated. Happy to merge the PR if you can revert the README change around this - perhaps adding a caveat of possibly having to SSH tunnel would be an appropriate compromise.

In the future I think making use of Traefik's recently added forward auth capability is something I'd like to take a look at - basic auth is a bit rubbish.

**Comment by addbee** [comment]
ah, i've already started work on some other changes so feel free to close this and merge in the bits you want.

Does this look like something you'd like to integrate? 
https://github.com/adam-bell/docker-compose-usenet

compose.sh generates command line based on the .env file for enabled services
services get split into files in services/ folder
up.sh does docker-compose up with the -f option to include correct yml files
down.sh does docker-compose down with the same.


still a work in progress

**Comment by stevewm** [comment]
I've merged the PR manually with the htpasswd changes - again, thanks for the contribution!

I'm intrigued by the idea of it being more modular. However, I'm not sure on the level of customisation wanted by those who use the project. I don't do any myself, given I originally wrote this for my own use (and so the services reflect what I use). I'm certainly not against it, I just want the project to remain as turnkey as possible - the less manual setup steps required the better, ideally zero.

Indeed, I had begun working on a script (plumber.sh) to connect all the services together - creating API keys, downloaders, indexers etc. [indexr](https://github.com/duhio/indexr) was something else in a similar vein I experimented with recently.

**Pull request closed without merging**
